#!/bin/bash

#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks-per-socket=2
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --time=02:00:00
#SBATCH --error=job.err
#SBATCH --output=job.out
#SBATCH --account=IscrB_HiMicro
#SBATCH --job-name=bader
#SBATCH --partition=m100_usr_prod
#SBATCH --qos=m100_qos_dbg

module purge
module load profile/chem-phys
module load python/3.8.2
module load autoload qe/6.7

export OMP_NUM_THREADS=8

QE_BIN='pp.x'
BADER_BIN='/m100/home/userexternal/rcheula0/bader/bader'

python3 bader.py -c True -w True -r False -p False

cd bader

mpirun $QE_BIN < pp_val.inp > pp_val.out
mpirun $QE_BIN < pp_all.inp > pp_all.out

$BADER_BIN charge_val.cube -ref charge_all.cube -vac auto -p all_atom > bader.out

cd ..

python3 bader.py -c True -w False -r False -p True
