#!/bin/bash

#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks-per-socket=2
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --time=02:00:00
#SBATCH --error=job.err
#SBATCH --output=job.out
#SBATCH --account=IscrB_HiMicro
#SBATCH --job-name=hop
#SBATCH --partition=m100_usr_prod
#SBATCH --qos=m100_qos_dbg

module purge
module load profile/chem-phys
module load python/3.8.2
module load autoload qe-gpu/6.7

export OMP_NUM_THREADS=8

QE_BIN='pw.x'

N_POOL=4

export ASE_ESPRESSO_COMMAND='mpirun -gpu --map-by socket:PE=$OMP_NUM_THREADS --rank-by core '$QE_BIN' -nk '$N_POOL' -inp espresso.pwi > espresso.pwo'

python3 hop.py
