#!/bin/bash

#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks-per-socket=2
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --time=02:00:00
#SBATCH --error=job.err
#SBATCH --output=job.out
#SBATCH --account=IscrB_HiMicro
#SBATCH --job-name=neb
#SBATCH --partition=m100_usr_prod
#SBATCH --qos=m100_qos_dbg

module purge
module load profile/chem-phys
module load python/3.8.2

#export OMP_NUM_THREADS=$(echo "$SLURM_CPUS_PER_TASK/$SLURM_NTASKS_PER_NODE"|bc)
export OMP_NUM_THREADS=8

QE_TYPE=develop

if [ "$QE_TYPE" == "develop" ]; then
    module load gnu/8.4.0
    module load openblas/0.3.9--gnu--8.4.0
    module load fftw/3.3.8--gnu--8.4.0
    module load hpc-sdk/2020--binary
    module load cuda/10.2
    module load spectrum_mpi/10.3.1--binary
    QE_BIN=$ESPRESSO_DEVELOP_DIR/neb.x
else
    module load autoload qe-gpu/6.7
    QE_BIN=neb.x
fi

inp_file=neb.inp
out_file=neb.out
py_file=neb.py
status_file=STATUS.txt

N_POOL=2

mpirun -gpu --map-by socket:PE=$OMP_NUM_THREADS --rank-by core $QE_BIN -nk $N_POOL -i $inp_file >> $out_file

autorestart=true

iter_max=4

if [ $autorestart = true ] && [[ -f $out_file && ! -f CRASH ]]; then
    grep -e 'activation energy (->)' $out_file | tail -1 >> $status_file
    grep -e 'activation energy (<-)' $out_file | tail -1 >> $status_file
    finish=$(grep -e 'neb: convergence achieved' -e 'neb: reached the maximum number of steps' $out_file)
    if [[ -n $finish ]]; then
        echo $finish >> $status_file
        if [[ -f $py_file ]]; then
            iter=$(grep -m 1 'iteration' $py_file | cut -d '=' -f 2 | sed 's/ //g')
            if [ "$iter_max" -gt "$iter" ]; then
                mkdir -p $iter
                cp $inp_file $iter && cp $out_file $iter && cp *.axsf $iter && cp *.crd $iter
                iter_new=$(echo "$iter" | awk '{printf "%.0f\n", $1+1}')
                echo 'ITERATION '$iter_new >> $status_file
                i_str=$(grep -m 1 'iteration' $py_file)
                i_newstr='iteration = '$iter_new
                sed -i -e "s/$i_str/$i_newstr/" $py_file
                python3 $py_file
                $BASH_SCRIPTS_DIR/run.sh neb
            fi
        fi
    else
        $BASH_SCRIPTS_DIR/run.sh -r neb
    fi
fi
